# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2243074910b097b231218b693acb9b14e230f5cb230f044bc784e22bed333a3e5ce473b14925afb661c3249893764d54a01a3fa506d3c828e2b1b1fd69c1a49

test:
  secret_key_base: 325d8837749a4c037518ce6abfa667ee4186ce1aaa1d68ca7d41e778380f982b2d59fb34a3cf5de43a3c6172c1285cd7e0791a1566cc2bc08d32742438884231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
